apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: app-of-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
      - name: backend
        image: gcr.io/cluster-01-271319/docker.io/library/httpd:latest-1
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["CHOWN", "MKNOD"]
          seccompProfile:
            type: "RuntimeDefault"
