apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: app-of-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: app-of-app
      containers:
      - name: backend
        image: mirror.gcr.io/library/nginx:1.23
        ports:
        - containerPort: 80

