apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: app-of-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mirror.gcr.io/library/nginx:1.23
        ports:
        - containerPort: 80
