apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/k8strainer/argo-app-of-apps.git'
    targetRevision: HEAD
    path: child-apps/backend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
