apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  #namespace: argocd
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/k8strainer/argo-app-of-app.git'
    targetRevision: main
    path: child-apps/frontend
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-of-app-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
